import type { ExperienceConfig } from "@/types";

export const experienceConfig: ExperienceConfig = {
  title: "Experience",

  positions: [
    {
      id: "job-1",
      title: "Software Engineer | Backend Developer",
      company: "Brain Socket",
      companyType: "Software Solutions",
      location: "Damascus, Syria",
      startDate: "March 2025",
      endDate: "",
      isCurrent: true,
      logo: "/brain_socket.png",
      companyUrl: "https://brain-socket.com/",
      description: [
        "Integrated Mailer, SMS, and Registra=on systems using Symfony, MongoDB, and KaDa, ensuring seamless communica=on and suppor=ng over 1,000 daily user interac=ons.",
        "Streamlined user account management processes across systems, reducing synchroniza=on errors by 25% through optimized creation, update, and permission handling.",
        "Enhanced real-time synchronization between master and sub-systems, improving overall system consistency and boosting operational eﬃciency by 30%.",
        "•	Scaled mother & baby e-commerce/community platform (momilly) from MVP → production (10K users); cut critical API latency from seconds → ~20ms; added Redis caching.",
      ],
      technologies: [
        "laravel",
        "symfony",
        "docker",
        "redis",
        "mySQL",
        "mongoDB",
        "apachekafka",
      ],
    },
    {
      id: "job-2",
      title: "Software Engineer, Data Analyst",
      company: "Stratum Admin",
      companyType: "Software medical soloution and consolting",
      location: "UK,Birmingham",
      startDate: "Feb 2025",
      endDate: "8/2025",
      isCurrent: false,
      logo: "/stratum.png",
      companyUrl: "https://www.linkedin.com/company/stratum-admin/",
      description: [
        "Led evaluation of the legacy system and database schema; defined requirements, authored technical reports, and aligned vendors on solution fit",
        "Supported hiring and delivery by shortlisting candidates, conducting technical interviews, and supervising implementation progress and quality",
        "Managed critical migration steps: database extraction and conversion, overseeing data cleaning and preparation for transfer",
      ],
      technologies: [
        "Agile Methodologies",
        "Data Management",
        "Data Analysis",
        "System analysis",
        "SQL Server",
        "Data Security",
      ],
    },
    {
      id: "job-3",
      title: "Full Stack Developer",
      company: "Software Solutions team",
      companyType: "Software Agency",
      location: "Damascus, Syria",
      startDate: "April 2020",
      endDate: "January 2025",
      isCurrent: false,
      logo: "",
      companyUrl: "",
      description: [
        "I worked as a freelance developer from 2021 to 2025, delivering 5 client projects that solved real business problems and achieved measurable results",
        "My roles depend on project I worked in mobile side in some project and a backend in others",
        "Full project details and outcomes are available in my portfolio, linked in my CV",
      ],
      technologies: [
        "Laravel",
        "Flutter",
        "HTML",
        "CSS",
        "javascript",
        "php",
        "codeigniter",
      ],
    },
    {
      id: "job-4",
      title: "Instructor RoboEc and Programming",
      company: "Syra Robo Academic",
      companyType: "Academic Institution",
      location: "Damascus, Syria",
      startDate: "December 2018",
      endDate: "September 2019",
      isCurrent: false,
      logo: "/syra_robot.jpg",
      companyUrl: "https://www.facebook.com/Syria.SyRARobot",
      description: [
        "Taught and mentored children and adolescents in foundational robotics and programming, focusing on EV3, Arduino, MBot, and Edison Robots.",
        "Trained over 150 students, fostering a passion for robotics, coding, and hands-on problem-solving.",
      ],
      technologies: [
        "Teaching",
        "Presentation",
        "Lego Ev3",
        "Arduino",
        "Python",
      ],
    },
  ],
};
