import type { ExperienceConfig } from "@/types";

export const experienceConfig: ExperienceConfig = {
  title: "Experience",

  positions: [
    {
      id: "job-1",
      title: "Software Engineer | Backend Developer",
      company: "Brain Socket",
      companyType: "Software Solutions",
      location: "Damascus, Syria",
      startDate: "February 2025",
      endDate: "",
      isCurrent: true,
      logo: "/brain_socket.png",
      companyUrl: "https://brain-socket.com/",
      description: [
        "Integrated Mailer, SMS, and Registra=on systems using Symfony, MongoDB, and KaDa, ensuring seamless communica=on and suppor=ng over 1,000 daily user interac=ons.",
        "Streamlined user account management processes across systems, reducing synchroniza=on errors by 25% through optimized creation, update, and permission handling.",
        "Enhanced real-time synchronization between master and sub-systems, improving overall system consistency and boosting operational eﬃciency by 30%.",
      ],
      technologies: [
        "Laravel",
        "Symfony",
        "Docker",
        "Redis",
        "MySQL",
        "MongoDB",
        "Kafka",
      ],
    },
    {
      id: "job-2",
      title: "Software Consultant, Data Analyst",
      company: "Al-Akkad Dental Center",
      companyType: "Clinic Dental Center",
      location: "Damascus, Syria",
      startDate: "December 2023",
      endDate: "Present",
      isCurrent: true,
      logo: "/akkad_dental.jpg",
      companyUrl: "https://www.facebook.com/AkkadDentalCenter",
      description: [
        "Provided technical consultation for evaluating the clinic’s existing software and team workflows, ensuring alignment with operational needs",
        "Analyzed 10 years of patient data and treatment records to identify actionable insights and optimize decision-making processes",
        "Designed a plan for migrating to a new system that meets evolving clinic requirements while preserving historical data integrity",
      ],
      technologies: [
        "Agile Methodologies",
        "Data Management",
        "Data Analysis",
        "SQL Server",
        "Data Security",
      ],
    },
    {
      id: "job-3",
      title: "Full Stack Developer",
      company: "Codrex Solutions",
      companyType: "Software Agency",
      location: "Dubai, UAE",
      startDate: "April 2021",
      endDate: "August 2021",
      isCurrent: false,
      logo: "/codrex_co.png",
      companyUrl: "https://codrex.co/",
      description: [
        "Contributed to the development of multiple web and mobile applications by assisting in backend and frontend implementation.",
        "Supported the digitization of business processes and improvement of operational workflows through web-based systems.",
        "Participated in building RESTful APIs, user interfaces, and database-driven features to enhance system efficiency and usability.",
        "Collaborated with the team to deliver scalable and user-friendly solutions across different domains",
      ],
      technologies: ["Laravel", "Flutter", "Pure HTML/CSS/JS"],
    },
    {
      id: "job-4",
      title: "Instructor RoboEc and Programming",
      company: "Syra Robo Academic",
      companyType: "Academic Institution",
      location: "Damascus, Syria",
      startDate: "December 2018",
      endDate: "September 2019",
      isCurrent: false,
      logo: "/syra_robot.jpg",
      companyUrl: "https://www.facebook.com/Syria.SyRARobot",
      description: [
        "Taught and mentored children and adolescents in foundational robotics and programming, focusing on EV3, Arduino, MBot, and Edison Robots.",
        "Trained over 150 students, fostering a passion for robotics, coding, and hands-on problem-solving.",
      ],
      technologies: [
        "Teaching",
        "Presentation",
        "Lego Ev3",
        "Arduino",
        "Python",
      ],
    },
  ],
};
